name: hello-gatsby
on: [push]
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Install required libraries
        run: sudo apt-get install zip -y
        
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install Project Dependencies
        run: npm ci
      
      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli
      
      - name: Build
        run: gatsby build
      
      - name: Verify build
        run: ls -la public
        
      - name: zip public directory
        run: zip -r gatsby-website.zip public
        
      - name: Verify zip file
        run: ls -la 
